### PR TITLE
timekeep: Update RTC_ATS_FILE path to match O changes

### PR DESCRIPTION
**Pull request by luk1337**
Change-Id: Ia4a35bc2c38516f5affce7436f2853aa66c28b95

### CODE REVIEW

**Comment by jerpelea** [comment]
this patch will break compatibility with pre O builds

**Comment by AdrianDC** [comment]
@jerpelea If this is merged, timekeep should now be branched for pre-o and master for o like the other projects with branches manifests updated appropriately I guess.

**Comment by luk1337** [comment]
better?

**Comment by luk1337** [comment]
actually nevermind, __ANDROID_API_O__ is probably undefined on pre-O.

**Comment by humberos** [comment]
sorry, it seems incomplete.
https://github.com/sonyxperiadev/timekeep/commit/04996642e2ffa21058ccdf91c8f47e0566a47c06
I think we'll need to change/update the path on userspace too...
which means that may we could create a new branch here as @AdrianDC pointed above.

**Comment by luk1337** [comment]
Oh, I didn't notice that. I'll take a look at that.

**Comment by AdrianDC** [comment]
Also I would rather use an ifeq / else to set the path instead of using an imprecise "ANDROID_OREO" definition that will be outdated on next releases.

**Comment by luk1337** [comment]
Fixed the userspace app.

**Comment by humberos** [comment]
@jerpelea 
IMO I think that branching is the cleaner way to proceed here and this patch should be done without #ifdefs.

**Comment by luk1337** [comment]
@AdrianDC what about current patch?

**Comment by AdrianDC** [comment]
That's better in my opinion, last time I checked that's what openssh did.

**Comment by jerpelea** [comment]
you can declare a legacy path and probe for it as a fallback

**Pull request merged**
