### PR TITLE
TimeKeep: Declare as VENDOR_MODULE

### PR DESCRIPTION
**Pull request by ix5**
Declaring `LOCAL_VENDOR_MODULE` means `TimeKeep.apk` will get installed to `/vendor/priv-app` instead of `/system/priv-app`, making it compatible with Treble ROMs.

<strike>Also change `LOCAL_PROPRIETARY_MODULE` to `LOCAL_VENDOR_MODULE` to keep consistency(VENDOR_MODULE is the "newer" and semantically more correct way).</strike> EDIT: Dropped because of backward compatibility, see below comments.

### CODE REVIEW

**Comment by jerpelea** [comment]
please split the commit in 2 separate commits

**Comment by ix5** [comment]
Done

**Comment by alviteri** [comment]
is this way used in old android versions ?

**Comment by ix5** [comment]
> is this way used in old android versions ?

What do you mean David? Are you referring to `PROPRIETARY`?

You can use `PROPRIETARY` or `VENDOR`, the effect is the same(afaics), only semantics differ. Since this is a a free/libre project, proprietary isn't really appropriate.

**Comment by alviteri** [comment]
I mean remember master branch is used for older android versions ... Make sure you don't break the build guide in older android versions ... Like nougat or marshmallow

**Comment by ix5** [comment]
Oh yes you're right, this would indeed break Nougat https://android.googlesource.com/platform/build/+/nougat-mr1-release/core/base_rules.mk#139

I will split off the commit

**Comment by ix5** [comment]
Done, you can build it on nougat now

**Pull request merged**
